#!/bin/sh -e

required=(file sudo tar zsh patch)

pkversion=$(awk -F'=' '/pkversion/ {print $2}' pkgutils.shared)

if [ $(id -u) -eq 0 ]; then
    echo "I'll ask you when I think I need root permissions, Ok?" >&2
    exit 1
fi

for i in $required; do
    if ! command -v $i > /dev/null 2>&1; then
        echo "Please install $i." >&2
        local stop=1
    fi
done
[ "$stop" = "1" ] && exit 1

case $(uname) in
    Linux)
        rtgrp=root
        ;;
    OpenBSD)
        rtgrp=wheel
        if ! command -v gtar > /dev/null 2>&1; then
            echo "Please install gtar, like this:" >&2
            echo "  pkg_add gtar" >&2
            exit 1
        fi
        ;;
esac

# Add support for doas
if ! command -v sudo > /dev/null 2>&1; then
    if command -v doas > /dev/null 2>&1; then
        alias sudo=doas
    else
        echo "Please install sudo." >&2
        exit 1
    fi
fi

echo "Setting the right permissions for the portsdir."
sudo chown -R ${USER}:$rtgrp /usr/sports

echo installing pkgutils
sudo install -m 755 -d                    /usr/local/lib
sudo install -m 644 pkgutils.shared       /usr/local/lib
sudo install -m 755 -d                    /usr/local/bin
sudo install -m 755 pkgadd                /usr/local/bin
sudo install -m 755 pkgrm                 /usr/local/bin
sudo install -m 755 pkginfo               /usr/local/bin
sudo install -m 755 pkgmk                 /usr/local/bin


echo "Creating work directories."
sudo install -d -g $rtgrp -o $USER /usr/pkgmk/source /usr/pkgmk/package /usr/pkgmk/work

echo "Creating database directory."
sudo install -d /var/package/rejects

# Don't overwrite existing config files.
[ -e /etc/pkgadd.conf ] || sudo install -m 644 pkgadd.conf           /etc/pkgadd.conf
[ -e /etc/pkgmk.conf ]  || sudo install -m 644 pkgmk.conf            /etc/pkgmk.conf

echo 'building the first port! pkgutils!'
pkgmk -f

if pkginfo -i pkgutils; then
    echo 'Updating pkgutils'
    sudo pkgadd -u /usr/pkgmk/package/pkgutils_$pkversion-1.pkg.tar.gz
else
    echo 'Installing pkgutils for the first time.'
    sudo pkgadd -i /usr/pkgmk/package/pkgutils_$pkversion-1.pkg.tar.gz
fi

echo "Setting the right permissions on the builddir."
sudo chown    ${USER}:$rtgrp /usr/pkgmk/*

cat << EOF
Congratulations, you have got sports installed. And you didn't even have to reboot. ;-)
For the next update of sports you can run:
  % cd /usr/sports/core/pkgutils
  % pkgmk -u
EOF
